### ISSUE TITLE
Consumes too much memory with longer MP3 files

### ISSUE THREAD

**Issue by faiface** [hajimehoshi/go-mp3#1]
I was just playing 'Stardust - Music Sounds Better With You' (6m44s long song) using the [example](https://github.com/hajimehoshi/go-mp3/tree/master/example) and it consumes 638MB of RAM. I think this is caused by ~reading~ decoding the whole file into the memory, instead of ~reading~ decoding it lazily on demand.

**Comment by hajimehoshi** [comment]
The whole file is just 11MB, so probably you mean decoding data?

**Comment by faiface** [comment]
Yeah, decoded, that's what I meant. Edited, thanks.

**Comment by hajimehoshi** [comment]
So 'seeking' feature is really required as you said before :-)

**Comment by faiface** [comment]
Well, almost. This is doable even without seking. But seekind would be nice too ;-)

**Comment by hajimehoshi** [comment]
Now it's fixed?

**Comment by faiface** [comment]
Seems fixed! No idea how those two lines fix it, but yeah, it seems fixed.

**Comment by hajimehoshi** [comment]
Thank you for confirming!

The `frame` is a smallest unit of decoding state, and all the frames were kept in the previous implementation.
