### ISSUE TITLE
MPEG2 support

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/go-mp3#12]
It seems ebiten cannot play certain mp3 files in mpeg format other than 1.

```
mp3: only MPEG version 1 (want 3; got 2) is supported
```

This means, we cannot always expect MP3 we download from the internet to work all the time, this is pretty inconvenient. Currently I am looking for a way to convert MPEG version on my own, but it would be nice if go-mp3 can support multiple versions.

**Comment by hajimehoshi** [comment]
First I need to buy and read the MP3 specification :-)

**Comment by K4thos** [comment]
got the same problem. Not sure how to understand the reply. Are there plans to implement support for MPEG2?

**Comment by hajimehoshi** [comment]
Not so far since I'm quite busy, but do you really need to play MPEG2 mp3 files like 22050 hz?

**Comment by K4thos** [comment]
hajimehoshi, thanks for reply. The file I tested was converted by me in audacity with default settings. I need mp3 support for an open source engine that allows players to use whatever supported resources they like. I'd prefer to avoid having to read bug reports saying that this and that particular mp3 file crashes the program. I'm not expecting the typical player to know the difference between MPEG1 and MPEG2 (hell, up till now even I didn’t know that this matters). No idea in which format most of the available music is in, but if MPEG2 has some adoption than I think it’s worth to implement.

**Comment by hajimehoshi** [comment]
The biggest difference between MPEG1 and MPEG2 (and 2.5) is the supported sample rate:
MPEG1: 32k - 48k [Hz]
MPEG2: 16k - 24k [Hz]
MPEG2.5: 8k - 12k [Hz]
See also: https://en.wikipedia.org/wiki/MP3#Bit_rate

I understand there are some demands to support MPEG2 and even 2.5, but the priority is still low to me. I  think 44100 [Hz] or 48000 [Hz] is the most typical sample rate, and the other sample rate is not so major.

**Comment by laice** [comment]
Get this error with MP3s returned from the Google Text to Speech API.  +1

**Comment by NLucasSoares** [comment]
> Get this error with MP3s returned from the Google Text to Speech API. +1

Would be wonderful to add for this purpose.

**Comment by tyrm** [comment]
Same issue with files from Amazon Polly :( +1

**Comment by mateusmaaia** [comment]
I am having the same issue when using  Google Text to Speech API. +1

**Comment by samm02** [comment]
Am having this issue with Amazon Polly also :( +1

**Comment by silverkt** [comment]
+1

**Comment by kvark128** [comment]
+1

**Comment by sunbin728** [comment]
+1

**Comment by 0xbkt** [comment]
+1

**Comment by hajimehoshi** [comment]
I don't have bandwidth now. I'm happy if someone could create PRs.
