### ISSUE TITLE
Missing "oto"

### ISSUE THREAD

**Issue by Firues** [hajimehoshi/go-mp3#14]
Where is "oto" from example code? 
"github.com/hajimehoshi/oto"

Thank you

**Comment by hajimehoshi** [comment]
You can install oto with `go get github.com/hajimehoshi/oto`.

Or, you can also do `go get -u github.com/hajimehoshi/go-mp3/example` that will install all dependencies of 'example' package.

**Comment by Firues** [comment]
Oh. Sorry. Okay.
Thank you, dear.

**Comment by hajimehoshi** [comment]
You're welcome :-) I'm happy you solved the problem
