### ISSUE TITLE
Seek(0, 0) and Read causes an unexpected error

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/go-mp3#16]
The following file is causing an error
```
call.mp3: MPEG ADTS, layer III, v1, 192 kbps, 44.1 kHz, JntStereo
```

error:
```
mp3: only layer3 (want 1; got 3) is supported
```

You can find this mp3 here.
https://maoudamashii.jokersounds.com/archives/se_maoudamashii_se_phone02.html

**Comment by hajimehoshi** [comment]
I could play this without errors. Do you use the latest ver?

I found another problem: The right side didn't play. This seems the same problem with #13

**Comment by hajimehoshi** [comment]
Oh I could reproduce this bug with `Seek(0, 0)`
