### ISSUE TITLE
Analysing samples?

### ISSUE THREAD

**Issue by ivoras** [hajimehoshi/go-mp3#29]
Hi,

What approach do you recommend if I want to analyse (not play) the decoded audio samples from the mp3 file? It appears that the Decoder only gives out bytes, and since samples are 2x16-bit values, what is the recommended way of getting a stream of such 2x16-bit samples?

**Comment by hajimehoshi** [comment]
Hi,

I am not sure I understand your question. Wouldn't just reading the bytes in your software work?

**Comment by ivoras** [comment]
I can read bytes but not 16 bit samples.
I can convert 4 bytes to 2x16 bit samples manually but that is very slow if done for each sample.

**Comment by hajimehoshi** [comment]
Yes, you need to convert the bytes to 16bit sequence. I don't think this is so slow in Go. Have you actually tried?

**Comment by ivoras** [comment]
It's not very slow :) just the conversion takes around 0.6 seconds for 100 MB of data on my Raspberry Pi (see the code at https://play.golang.org/p/VZKuJ4_d5xc ). 

So, it's ok, but looking at https://github.com/hajimehoshi/go-mp3/blob/master/internal/frame/frame.go#L659 it seems that the code is already converting 16-bit samples to a stream of bytes, and my code would do this in reverse, so maybe there's an opportunity for optimisation here.

Anyway, thanks for the good work!

**Comment by hajimehoshi** [comment]
Yes, I admit there is a room to improve the performance, but I adopted the simplicity of the API. As there is a request to treat the mono stream as it is (https://github.com/hajimehoshi/go-mp3/pull/20), I might rethink the API later.

Thank you for using go-mp3!
