### ISSUE TITLE
Usage to cut mp3 segment

### ISSUE THREAD

**Issue by CAIJUNYI** [hajimehoshi/go-mp3#32]
i am using go-mp3 to cut mp3 file, but encountered the problem shown as follows:
i defined the size of 441000 bytes, but got only 1368 bytes.  Why?

![mp3](https://user-images.githubusercontent.com/10704251/63857790-e98c9680-c9d6-11e9-9425-f8da97c53a42.png)

The following is my code:
```go
package main

import (
	"fmt"
	"io"
	"io/ioutil"
	"os"

	"github.com/hajimehoshi/go-mp3"
)

func main() {
	buf, err := readMP3("34YBAFdskzmAUMlOADSMOxgm3l4714.mp3")
	if err != nil {
		fmt.Println(err)
	}

	err = ioutil.WriteFile("output.mp3", buf, os.ModePerm)
	if err != nil {
		fmt.Println(err)
	}
}

func readMP3(file string) ([]byte, error) {
	f, err := os.Open(file)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	d, err := mp3.NewDecoder(f)
	if err != nil {
		return nil, err
	}
	fmt.Println("mp3 length: ", d.Length())

	st := 10
	et := 20

	startPos := byteOfSecond(st, d.SampleRate())
	endPos := byteOfSecond(et, d.SampleRate())
	size := endPos - startPos
	// seek to the start position
	pos, err := d.Seek(int64(startPos), io.SeekStart)
	if err != nil {
		return nil, err
	}
	fmt.Println("current pos", pos)

	buf := make([]byte, size)
	n, err := d.Read(buf)
	if err != nil {
		return nil, err
	}
	fmt.Printf("readed %d bytes from mp3 file\n", n)

	return buf, nil
}

func byteOfSecond(sec int, freq int) int {
	return sec * freq
}
```

**Comment by hajimehoshi** [comment]
Hi,

`io.Reader` doesn't guarantee how many bytes are read: https://golang.org/pkg/io/#Reader this might be 0 bytes in an extreme case.

You can use `io.ReadFull` to fill the bytes: https://golang.org/pkg/io/#ReadFull

**Comment by dudk** [comment]
@CAIJUNYI if you plan to do more complicated manipulations with audio - you can consider to use [pipelined/pipe](https://github.com/pipelined/pipe) framework. It has [mp3 component](https://github.com/pipelined/pipe) based on this wonderful library by Hajime.

An example of the case that is close to what you're trying to do is available [here](https://github.com/pipelined/example/blob/master/example4.go).

**Comment by CAIJUNYI** [comment]
@dudk Thanks a lot! The example is really helpful!

**Comment by CAIJUNYI** [comment]
@hajimehoshi Using `io.ReadFull` can get the full size of buffer. Thx!
