### ISSUE TITLE
Help: Conversion to pcm_s16le or any other raw data type

### ISSUE THREAD

**Issue by D-sense** [hajimehoshi/go-mp3#33]
Please does this package support conversion to pcm_s16le or any other raw data type?

**Comment by hajimehoshi** [comment]
Not sure what the 'raw' data means. From 8bit, you can implement by yourself: https://github.com/hajimehoshi/ebiten/blob/master/audio/internal/convert/stereo16.go

**Comment by dudk** [comment]
@D-sense you can try to use [pipelined framework](https://godoc.org/pipelined.dev/example).

**Comment by D-sense** [comment]
> @D-sense you can try to use [pipelined framework](https://godoc.org/pipelined.dev/example).

Thanks. Actually, the pipelined framework offers the opposite of what I need. It processes a "wav" to mp3 and so on. I need to process/transcode mp3 to wav/pcm formats

**Comment by dudk** [comment]
@D-sense there are [mp3.Pump](https://godoc.org/pipelined.dev/mp3#Pump) and [wav.Sink](https://godoc.org/pipelined.dev/wav#Sink) types that will allow you to do what you want.

**Comment by hajimehoshi** [comment]
> By "raw data", I meant transcoding the file wth a pcm_s16le codec.

This package does so :)

**Comment by D-sense** [comment]
> > By "raw data", I meant transcoding the file wth a pcm_s16le codec.
> 
> This package does so :)

Please, could you provide me with an example? I'm kinda lost of how this can be achieved because the provided example only produces bytes. How can I take it further?
Thank you

**Comment by hajimehoshi** [comment]
The produced bytes `Decoder` produces are already pcm singed 16bit little endian. Perhaps, are you talking about how to use `io.Reader`?

**Comment by D-sense** [comment]
> The produced bytes `Decoder` produces are already pcm singed 16bit little endian. Perhaps, are you talking about how to use `io.Reader`?

No, I do not need help with io.Reader.
Yes, I noticed the produced PCM signed 16bit little-endian. Is there a way I can convert it from 16bit little-endian to 32bit little-endian. This script (you can see it that is uses codec pcm_f32le) runs my code well:
```
ffmpeg -v quiet -i 1479012090.ts -f f32le -ac 1 -c:a pcm_f32le -ar 44100 pipe:1 | ./cmd /dev/stdin
```
That script outputs an accurate result. But I need to do this in my code (not in CLI).


Below is my code:
```
package main

import (
	"bytes"
	"encoding/binary"
	"flag"
	"fmt"
	"github.com/benjojo/bpm"
	"github.com/hajimehoshi/go-mp3"
	"io"
	"log"
	"math"
	"os"
)

var (
	min                 = flag.Float64("min", 40, "min BPM you are expecting")
	max                 = flag.Float64("max", 200, "max BPM you are expecting")
)

func main(){
	f, err := os.Open("../test_tracks/new1.mp3")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	file, err := mp3.NewDecoder(f)
	if err != nil {
		log.Fatal(err)
	}

	byteFile, err := streamToByte(file)
	if err != nil {
		log.Fatal("could not ", err)
	}

	floatFile := ToFloat32(byteFile)

	bpm.ReadFloatArray(floatFile)

	fmt.Printf("%f\n", bpm.ScanForBpm(floatFile, *min, *max, 1024, 1024))
}


func streamToByte(stream io.Reader) ([]byte, error) {
	buf := new(bytes.Buffer)
	_, err := buf.ReadFrom(stream)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func ToFloat32(bytes []byte) []float32 {
	result  := make([]float32, 1)

	bits := binary.LittleEndian.Uint32(bytes)
	float := math.Float32frombits(bits)
	result = append(result, float)

	return result
}
```

The goal is to use your package to convert MP3 with codec pcm_sle32, then supply the result to a method from the BPM package in order to get the audio file's BPM. Currently, I am getting the same result for different audio tracks (that is not supposed to happen). This is because I am still not supplying the BPM package with the right raw data (i.e., pcm_sle32).

Thank you for your help.

**Comment by hajimehoshi** [comment]
I don't know anything about BPM library.

So you want to convert 16bit singed integer to 32bit signed float, right?

```
    result  := make([]float32, 1)

    bits := binary.LittleEndian.Uint32(bytes)
    float := math.Float32frombits(bits)
    result = append(result, float)
```

This should be
```
    var result []float32

    for i := 0; len(bytes)/2; i++ {
        s16 := int16(binary.LittleEndian.Uint16(bytes[i]))
	float := float32(s16) / 32768
        result = append(result, float)
    }
```

**Comment by D-sense** [comment]
> I don't know anything about BPM library.
> 
> So you want to convert 16bit singed integer to 32bit signed float, right?
> 
> ```
>     result  := make([]float32, 1)
> 
>     bits := binary.LittleEndian.Uint32(bytes)
>     float := math.Float32frombits(bits)
>     result = append(result, float)
> ```
> 
> This should be
> 
> ```
>     var result []float32
> 
>     for i := 0; len(bytes)/2; i++ {
>         s16 := int16(binary.LittleEndian.Uint16(bytes[2*i:2*i+2]))
> 	float := float32(s16) / 32768
>         result = append(result, float)
>     }
> ```

Thank you @hajimehoshi 
But this snippet "len(bytes)/2" is wrong in the loop.

**Comment by hajimehoshi** [comment]
I've not confirmed this worked, but something like that should work :-)

**Comment by D-sense** [comment]
> I've not confirmed this worked, but something like this should work :-)

Thanks a lot, @hajimehoshi. I modified it further to:
```
var result []float32
for i := 0; i < len(bytes)/2; i++ {
		s16 := int16(binary.LittleEndian.Uint16(bytes[2*i:2*i+2]))
		float := float32(s16) / 32768
		result = append(result, float)
}
```

Everything is working perfectly now and I am able to get the correct BPM.

I appreciate your assistance :)

**Comment by hajimehoshi** [comment]
No problem!
