### ISSUE TITLE
how to get mp3 paly duration

### ISSUE THREAD

**Issue by tuoling805** [hajimehoshi/go-mp3#38]

**Comment by hajimehoshi** [comment]
Use https://godoc.org/github.com/hajimehoshi/go-mp3#Decoder.Length

**Comment by tuoling805** [comment]
Decoder.Length get the mp3 length,
my code

f, err := os.Open("a.mp3")
	if err != nil {
	}
	defer f.Close()

	d, err := mp3.NewDecoder(f)
	if err != nil {
	}

	fmt.Printf("Length: %d[bytes]\n", d.Length())


then ,I need get the a.mp3  playback duration
with the second identification

**Comment by tuoling805** [comment]
thanks

**Comment by hajimehoshi** [comment]
You can calculate the length in seconds like

`d.Length() / d.SampleRate() / 4`

(4 is stereo (2) * 16bit in bytes (2))

**Comment by tuoling805** [comment]
thanks , the problem solving
