### ISSUE TITLE
Change speed while reproducing

### ISSUE THREAD

**Issue by baldore** [hajimehoshi/go-mp3#46]
Hello, thanks for this great library. I was wondering if there's a way to change the speed while reproducing an mp3 file. I don't have experience working with mp3 at this level so this is more a beginner question. 

Thanks in advance.

**Comment by hajimehoshi** [comment]
Hi. Changing the speed is not an MP3 decoder's responsibility. You would have to modify the result by yourself. I'm afraid I don' know a good library in Go for this purpose.

**Comment by baldore** [comment]
I see. Thanks a lot for the quick response.
