### ISSUE TITLE
Large repo

### ISSUE THREAD

**Issue by jpillora** [hajimehoshi/go-mp3#5]
Awesome work!

All go gets for `github.com/hajimehoshi/go-mp3` will include the 10MB example mp3, useful for testing though maybe a shell script to `wget` the example file might be better? However, this would require git history change which isn't optimal either...

**Comment by hajimehoshi** [comment]
I understand the problem, but unfortunately breaking the git repository history is the only way to solve this. I'm afraid I won't do this. Thank you.
