### ISSUE TITLE
Rename example to _example

### ISSUE THREAD

**Issue by emersion** [hajimehoshi/go-mp3#8]
Otherwise an `example` binary is built and placed in `$GOPATH/bin` when `go get`-ing the library.

**Comment by hajimehoshi** [comment]
That makes sense.

**Comment by hajimehoshi** [comment]
BTW, I prefer using tag `example` for this case to avoid installing the example binary by `go get -u github.com/hajimehoshi/go-mp3/...`, but I'd like to know @faiface and @alistanis 's opinions just in case.
