### ISSUE TITLE
mp3: only layer3 (want 1; got 3) is supported!

### ISSUE THREAD

**Issue by wallnutkraken** [hajimehoshi/go-mp3#9]
**Steps to reproduce:**

1. Open this file: http://www.podtrac.com/pts/redirect.mp3/traffic.libsyn.com/cortex/Cortex_053.mp3 
2. call `Decode()` on the file

**Expected result:**
The file is decoded successfully.

**Actual result:**
The function returns an error saying `mp3: only layer3 (want 1; got 3) is supported!`

**Notes:**
Some other files work perfectly fine, for example:
http://www.podtrac.com/pts/redirect.mp3/traffic.libsyn.com/cortex/Cortex_007.mp3

**Comment by hajimehoshi** [comment]
Thanks, reproduced.

**Comment by hajimehoshi** [comment]
@alistanis Do you have any suggestion? I feel like go-mp3 should consider tags.

**Comment by hajimehoshi** [comment]
Fixed.
